#ifndef _CUHOOK_H_
#define _CUHOOK_H_

typedef enum HookSymbolsEnum {
    CU_HOOK_CTX_GET_CURRENT,
    CU_HOOK_CTX_SET_CURRENT,
    CU_HOOK_CTX_CREATE,
    CU_HOOK_CTX_DESTROY,
    CU_HOOK_CTX_POP_CURRENT,
    CU_HOOK_CTX_PUSH_CURRENT,
    CU_HOOK_DEVICE_PRIMARY_CTX_RETAIN,
    CU_HOOK_DEVICE_PRIMARY_CTX_RESET,
    CU_HOOK_DEVICE_PRIMARY_CTX_RELEASE,
    CU_HOOK_LAUNCH_KERNEL,
    CU_HOOK_LAUNCH_COOPERATIVE_KERNEL,
    CU_HOOK_CTX_SYNC,
    CU_HOOK_GET_PROC_ADDRESS,
    NUM_HOOK_SYMBOLS,
} HookSymbols;

#endif /* _CUHOOK_H_ */